version: '3.8'

services:
  database:
    image: postgres:12.6
    environment:
      POSTGRES_USER: cs2102-project
      POSTGRES_PASSWORD: cs2102-project
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./views.sql:/docker-entrypoint-initdb.d/2-views.sql
      - ./triggers.sql:/docker-entrypoint-initdb.d/3-triggers.sql
      - ./input.sql:/docker-entrypoint-initdb.d/4-input.sql
      - ./custom_types.sql:/docker-entrypoint-initdb.d/5-custom_types.sql 
      - ./functions.sql:/docker-entrypoint-initdb.d/6-functions.sql
      